apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "steel-dart.fullname" . }}-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        envFrom:
        - secretRef:
            name: {{ .Values.secretRef }}
        command: ['sh', '-c', 'php artisan migrate --force']
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  backoffLimit: {{ .Values.job.backoffLimit }}
