apiVersion: v1
kind: Secret
metadata:
  name: steel-dart-env
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- $envFile := printf "files/%s" .Values.envFileName }}
{{- with .Files.Glob $envFile }}
{{- range . }}
  {{ base (index . 0) }}: {{ index . 1 | b64enc | quote }}
{{- end }}
{{- end }}
